---
title: "creates_plots"
author: "Christopher"
date: "2026-03-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This loads the packages:

```{r cars}
library(tidyverse)
library(ggcorrplot)
library(patchwork)
```

This loads the data:

```{r pressure, echo=FALSE}
data_final <- read.csv("data/final_data/final.data.csv")
```

Now we want to create a correlation matrix:

```{r}
data_corr <- data_final %>% distinct(GPT_FAM_ft, GPT_concr, GPT_arou, GPT_val, GPT_arou, GPT_AoA_ft, .keep_all = TRUE) %>% select(GPT_FAM_ft, GPT_concr, GPT_arou, GPT_val, GPT_arou, GPT_AoA_ft, surprisal_2_words_context, entropy_2_words_context, frequency, zipf_frequency)

data_corr_p1 <- data_corr %>% select(GPT_FAM_ft, GPT_concr, GPT_val, GPT_arou, GPT_AoA_ft)
data_corr_p2 <- data_corr %>% select(GPT_FAM_ft, surprisal_2_words_context, entropy_2_words_context, frequency, zipf_frequency)
data_corr_p3 <- data_corr %>% select(GPT_concr, surprisal_2_words_context, entropy_2_words_context, frequency, zipf_frequency)
data_corr_p4 <- data_corr %>% select(GPT_val, surprisal_2_words_context, entropy_2_words_context, frequency, zipf_frequency)
data_corr_p5 <- data_corr %>% select(GPT_arou, surprisal_2_words_context, entropy_2_words_context, frequency, zipf_frequency)
data_corr_p6 <- data_corr %>% select(GPT_AoA_ft, surprisal_2_words_context, entropy_2_words_context, frequency, zipf_frequency)

corr_p1 <- round(cor(data_corr_p1, use = "pairwise.complete.obs"), 2)
corr_p2 <- round(cor(data_corr_p2, use = "pairwise.complete.obs"), 2)
corr_p3 <- round(cor(data_corr_p3, use = "pairwise.complete.obs"), 2)
corr_p4 <- round(cor(data_corr_p4, use = "pairwise.complete.obs"), 2)
corr_p5 <- round(cor(data_corr_p5, use = "pairwise.complete.obs"), 2)
corr_p6 <- round(cor(data_corr_p6, use = "pairwise.complete.obs"), 2)

p1 <- ggcorrplot(corr_p1, method = "circle", lab = TRUE)
p2 <- ggcorrplot(corr_p2, method = "circle", lab = TRUE)
p3 <- ggcorrplot(corr_p3, method = "circle", lab = TRUE)
p4 <- ggcorrplot(corr_p4, method = "circle", lab = TRUE)
p5 <- ggcorrplot(corr_p5, method = "circle", lab = TRUE)
p6 <- ggcorrplot(corr_p6, method = "circle", lab = TRUE)

ggsave("figures/project/plots/ratings_corr.png", plot = p1, width = 8, height = 6)
ggsave("figures/project/plots/familiarity_corr.png", plot = p2, width = 8, height = 6)
ggsave("figures/project/plots/concreteness_corr.png", plot = p3, width = 8, height = 6)
ggsave("figures/project/plots/valence_corr.png", plot = p4, width = 8, height = 6)
ggsave("figures/project/plots/arousal_corr.png", plot = p5, width = 8, height = 6)
ggsave("figures/project/plots/age_of_acquisition_corr.png", plot = p6, width = 8, height = 6)
```

This will also create a distribution plot:

```{r}
p7 <- ggplot(data_corr, aes(x = GPT_FAM_ft)) +
  geom_histogram(fill = "blue") 

p8 <- ggplot(data_corr, aes(x = GPT_concr)) +
  geom_histogram(fill = "blue") 

p9 <- ggplot(data_corr, aes(x = GPT_val)) +
  geom_histogram(fill = "blue") 

p10 <- ggplot(data_corr, aes(x = GPT_arou)) +
  geom_histogram(fill = "blue") 

p11 <- ggplot(data_corr, aes(x = GPT_AoA_ft)) +
  geom_histogram(fill = "blue") 

ggsave("figures/project/plots/distribution.png", plot = p7+p8+p9+p10+p11)

```
