---
title: "replication"
author: "Christopher"
date: "2026-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## loading the packages

```{r}
library(tidyverse)
```

## loading the data

```{r}
## GPT estimates from Conde et al. (2026):
conde_estimates <- read.csv("pre_data/conde_concreteness_valence_arousal_aoa.csv", sep = ";")

## GPT estimates generated by myself:
familiarity_replication <- read_csv("GPTreplication/familiarity_replication.csv")
concreteness_replication <- read_csv("GPTreplication/concreteness_replication.csv")
valence_replication <- read_csv("GPTreplication/valence_replication.csv")
arousal_replication <- read_csv("GPTreplication/arousal_replication.csv")
aoa_replication <- read.csv("GPTreplication/aoa_ft.csv", sep = ";") ## ft prompt both for finetuning as well as generation.
```

# preprocessing

```{r}
#### This is an example why it is important that the variable we want to replicate is distributed across the whole possible range:

# two datasets, data2 has one extra row:
data1 <- data.frame(predictorA = c(6.95, 6.94, 7), predictorB = c(6.57, 6.92, 6.95)) ## data1 does not include the whole range of familiarity ratings (1-7, but practically 3.5-7).
data2 <- data.frame(predictorA = c(6.95, 6.94, 7, 3.5), predictorB = c(6.57, 6.92, 6.95, 3.52)) ## data2 does include one datapoint at the lowest possible point in the practical range.
# Pearson correlation:
cor(data1$predictorA, data1$predictorB, method = "pearson") ## 0.4245658
cor(data2$predictorA, data2$predictorB, method = "pearson") ## 0.995114

## => The Pearson correlation between both are radically different.
## => This shows that having a dataset which contains only a very specific subgroub of the range, for example only 4.0-4.3 or only 6.9-7.0, will result in a low Pearson correlation, since then the outputs of the LLM (which are not deterministic) will seem relatively (!) inaccurate, which can be solved fast by increasing variance through a rating that is further away from that area of the range.

#### This is the procedure how the 10.000 rows were selected ensuring that no scenarios like the above one happen:

## This ensures that the distribution of the GPT_FAM ratings is rougly equal across the possible range. It is limited on the bottom, since there are no ratings lower than 3.5.


## This divides the whole dataset from Conde et al. (2026) into four categories based on the GPT_FAM column: 
# 1. ratings from 6 or higher to 7; from 5 to 6; from 4 to 5; from 3 to 4;
rep_data_1 <-conde_estimates[conde_estimates$GPT_FAM >= 6 & conde_estimates$GPT_FAM <= 7, ] 
rep_data_2 <-conde_estimates[conde_estimates$GPT_FAM >= 5 & conde_estimates$GPT_FAM <= 6, ]
rep_data_3 <-conde_estimates[conde_estimates$GPT_FAM >= 4 & conde_estimates$GPT_FAM <= 5, ]
rep_data_4 <-conde_estimates[conde_estimates$GPT_FAM >= 3 & conde_estimates$GPT_FAM <= 4, ]

# This picks the first 2500 words from these four categories and creates a dataframe each.
rep_data_1 <- rep_data_1 %>% slice(1:2500)
rep_data_2 <- rep_data_2 %>% slice(1:2500)
rep_data_3 <- rep_data_3 %>% slice(1:2500)
rep_data_4 <- rep_data_4 %>% slice(1:2500)

# This adds a category column:
rep_data_1$category <- "A"
rep_data_2$category <- "B"
rep_data_3$category <- "C"
rep_data_4$category <- "D"

# This binds all four datasets into one dataset containing 10.000 words.
rep_data <- rbind(rep_data_1, rep_data_2, rep_data_3, rep_data_4)

## making the columns numeric:
rep_data$GPT_FAM <- as.numeric(gsub(",", ".", rep_data$GPT_FAM))
rep_data$GPT_concr <- as.numeric(gsub(",", ".", rep_data$GPT_concr))
rep_data$GPT_arou <- as.numeric(gsub(",", ".", rep_data$GPT_arou))
rep_data$GPT_val <- as.numeric(gsub(",", ".", rep_data$GPT_val))
rep_data$GPT_AoA_ft <- as.numeric(gsub(",", ".", rep_data$GPT_AoA_ft))

## Important: While the restriction categories start with 3 and go up to 7 for GPT_FAM, this does not mean that f.e. GPT_concr cannot have a rating below 3. This is simply a selection mechanism for picking rows. In general, GPT_FAM can have values from 3.5 to 7; GPT_concr, GPT_val, and GPT_arou can have values from 1 to 7; and GPT_AoA_ft can have values from 2 to 20.
rep_data_a <- rep_data %>% select(Word)

#writexl::write_xlsx(rep_data_a, "replication.xlsx")

```

## loading the OpenAI output for the words remaining without GPT familiarity estimate:

```{r}
### Sometimes the output file from OpenAI uses "/" insetad of "." seperators; using this line of code it defaults to the point seperator
names(familiarity_replication) <- gsub("/", ".", names(familiarity_replication))

### This reduces the dataframe to only the required columns: ##select for columns, distinct for rows
familiarity_replication <- familiarity_replication %>% distinct(custom_id, response.body.choices.0.logprobs.content.0.top_logprobs.0.token, response.body.choices.0.logprobs.content.0.top_logprobs.0.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.1.token, response.body.choices.0.logprobs.content.0.top_logprobs.1.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.2.token, response.body.choices.0.logprobs.content.0.top_logprobs.2.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.3.token, response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.4.token, response.body.choices.0.logprobs.content.0.top_logprobs.4.logprob)


### This renames the columns of the dataframe:
familiarity_replication <- familiarity_replication %>% rename(word_nr = custom_id, token_1 = response.body.choices.0.logprobs.content.0.top_logprobs.0.token, logprob_1 = response.body.choices.0.logprobs.content.0.top_logprobs.0.logprob, token_2 = response.body.choices.0.logprobs.content.0.top_logprobs.1.token, logprob_2 = response.body.choices.0.logprobs.content.0.top_logprobs.1.logprob, token_3 = response.body.choices.0.logprobs.content.0.top_logprobs.2.token, logprob_3 = response.body.choices.0.logprobs.content.0.top_logprobs.2.logprob, token_4 = response.body.choices.0.logprobs.content.0.top_logprobs.3.token, logprob_4 = response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, token_5 = response.body.choices.0.logprobs.content.0.top_logprobs.4.token, logprob_5 = response.body.choices.0.logprobs.content.0.top_logprobs.4.logprob)


### This generates the probabilities for a token based of the logprobability:
familiarity_replication$prob_1 <- exp(familiarity_replication$logprob_1)
familiarity_replication$prob_2 <- exp(familiarity_replication$logprob_2)
familiarity_replication$prob_3 <- exp(familiarity_replication$logprob_3)
familiarity_replication$prob_4 <- exp(familiarity_replication$logprob_4)
familiarity_replication$prob_5 <- exp(familiarity_replication$logprob_5)


### This code makes all token-columns to be characters. This is necessary for the next step.
familiarity_replication$token_1 <- as.character(familiarity_replication$token_1)
familiarity_replication$token_2 <- as.character(familiarity_replication$token_2)
familiarity_replication$token_3 <- as.character(familiarity_replication$token_3)
familiarity_replication$token_4 <- as.character(familiarity_replication$token_4)
familiarity_replication$token_5 <- as.character(familiarity_replication$token_5)


### This will clean the token_columns, since often they do not contain strictly numbers from 1-7 but also written numbers, or number from different languages. Sometimes even numbers outside of the range of 1-7, or words like "Neutral".
familiarity_replication <- familiarity_replication %>% mutate(token_2 = recode(token_2, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "seven" = "7", "sieben" = "7", "siete" = "7", "six" = "6", "六" = "6"))
familiarity_replication <- familiarity_replication %>% mutate(token_3 = recode(token_3, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "seven" = "7", "sieben" = "7", "siete" = "7", "six" = "6", "六" = "6"))
familiarity_replication <- familiarity_replication %>% mutate(token_4 = recode(token_4, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "seven" = "7", "sieben" = "7", "siete" = "7", "six" = "6", "六" = "6"))
familiarity_replication <- familiarity_replication %>% mutate(token_5 = recode(token_5, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "seven" = "7", "sieben" = "7", "siete" = "7", "six" = "6", "六" = "6"))

familiarity_replication <- familiarity_replication %>% mutate(
    token_4 = na_if(token_4, "0"))
familiarity_replication <- familiarity_replication %>% mutate(
    token_5 = na_if(token_5, "0"))

## This code checks which values are found in a given column (best would be only 1-7):
unique(familiarity_replication$token_1)
unique(familiarity_replication$token_2)
unique(familiarity_replication$token_3)
unique(familiarity_replication$token_4)
unique(familiarity_replication$token_5)

### This code makes all columns numeric:
familiarity_replication$token_1 <- as.numeric(familiarity_replication$token_1) #=>Token-Columns
familiarity_replication$token_2 <- as.numeric(familiarity_replication$token_2)
familiarity_replication$token_3 <- as.numeric(familiarity_replication$token_3)
familiarity_replication$token_4 <- as.numeric(familiarity_replication$token_4)
familiarity_replication$token_5 <- as.numeric(familiarity_replication$token_5)
familiarity_replication$prob_1 <- as.numeric(familiarity_replication$prob_1) #=>Probability-columns
familiarity_replication$prob_2 <- as.numeric(familiarity_replication$prob_2)
familiarity_replication$prob_3 <- as.numeric(familiarity_replication$prob_3)
familiarity_replication$prob_4 <- as.numeric(familiarity_replication$prob_4)
familiarity_replication$prob_5 <- as.numeric(familiarity_replication$prob_5)

### this calculates how many tokens ended up being used for the weighted sum
familiarity_replication$n_tokens_used <- rowSums(!is.na(cbind(
  familiarity_replication$token_1,
  familiarity_replication$token_2,
  familiarity_replication$token_3,
  familiarity_replication$token_4,
  familiarity_replication$token_5)))

mean(familiarity_replication$n_tokens_used) ## 4.98 tokens were used on average.
min(familiarity_replication$n_tokens_used) # 4 tokens was the minimum
max(familiarity_replication$n_tokens_used) # 5 tokens was the maximum (more is not possible)

### Now we will generate the weighted_sum based on the tokens and their probabilities:

familiarity <- function(familiarity_replication) {
  rowSums(cbind(
    familiarity_replication$token_1 * familiarity_replication$prob_1,
    familiarity_replication$token_2 * familiarity_replication$prob_2,
    familiarity_replication$token_3 * familiarity_replication$prob_3,
    familiarity_replication$token_4 * familiarity_replication$prob_4,
    familiarity_replication$token_5 * familiarity_replication$prob_5
  ), na.rm = TRUE)}

### This code will add the output as a column:
familiarity_replication$familiarity_replication <- familiarity(familiarity_replication)

familiarity_replication$familiarity_replication <- round(familiarity_replication$familiarity_replication, 2)

familiarity_replication <- familiarity_replication %>% select(familiarity_replication)
```

## loading the OpenAI output for the words remaining without GPT familiarity estimate:


```{r}
### Sometimes the output file from OpenAI uses "/" insetad of "." seperators; using this line of code it defaults to the point seperator
names(concreteness_replication) <- gsub("/", ".", names(concreteness_replication))

### This reduces the dataframe to only the required columns: ##select for columns, distinct for rows
concreteness_replication <- concreteness_replication %>% distinct(custom_id, response.body.choices.0.logprobs.content.0.top_logprobs.0.token, response.body.choices.0.logprobs.content.0.top_logprobs.0.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.1.token, response.body.choices.0.logprobs.content.0.top_logprobs.1.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.2.token, response.body.choices.0.logprobs.content.0.top_logprobs.2.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.3.token, response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.4.token, response.body.choices.0.logprobs.content.0.top_logprobs.4.logprob)


### This renames the columns of the dataframe:
concreteness_replication <- concreteness_replication %>% rename(word_nr = custom_id, token_1 = response.body.choices.0.logprobs.content.0.top_logprobs.0.token, logprob_1 = response.body.choices.0.logprobs.content.0.top_logprobs.0.logprob, token_2 = response.body.choices.0.logprobs.content.0.top_logprobs.1.token, logprob_2 = response.body.choices.0.logprobs.content.0.top_logprobs.1.logprob, token_3 = response.body.choices.0.logprobs.content.0.top_logprobs.2.token, logprob_3 = response.body.choices.0.logprobs.content.0.top_logprobs.2.logprob, token_4 = response.body.choices.0.logprobs.content.0.top_logprobs.3.token, logprob_4 = response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, token_5 = response.body.choices.0.logprobs.content.0.top_logprobs.4.token, logprob_5 = response.body.choices.0.logprobs.content.0.top_logprobs.4.logprob)


### This generates the probabilities for a token based of the logprobability:
concreteness_replication$prob_1 <- exp(concreteness_replication$logprob_1)
concreteness_replication$prob_2 <- exp(concreteness_replication$logprob_2)
concreteness_replication$prob_3 <- exp(concreteness_replication$logprob_3)
concreteness_replication$prob_4 <- exp(concreteness_replication$logprob_4)
concreteness_replication$prob_5 <- exp(concreteness_replication$logprob_5)


### This code makes all token-columns to be characters. This is necessary for the next step.
concreteness_replication$token_1 <- as.character(concreteness_replication$token_1)
concreteness_replication$token_2 <- as.character(concreteness_replication$token_2)
concreteness_replication$token_3 <- as.character(concreteness_replication$token_3)
concreteness_replication$token_4 <- as.character(concreteness_replication$token_4)
concreteness_replication$token_5 <- as.character(concreteness_replication$token_5)


### This will clean the token_columns, since often they do not contain strictly numbers from 1-7 but also written numbers, or number from different languages. Sometimes even numbers outside of the range of 1-7, or words like "Neutral".
concreteness_replication <- concreteness_replication %>% mutate(token_2 = recode(token_2, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "cinco" = "5", "siete" = "7", "sieben" = "7", "seven" = "7", "six" = "6", "六" = "6"))

concreteness_replication <- concreteness_replication %>% mutate(token_3 = recode(token_3, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "cinco" = "5", "siete" = "7", "sieben" = "7", "seven" = "7", "six" = "6", "六" = "6"))

concreteness_replication <- concreteness_replication %>% mutate(token_4 = recode(token_4, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "cinco" = "5", "siete" = "7", "sieben" = "7", "seven" = "7", "six" = "6", "六" = "6"))

concreteness_replication <- concreteness_replication %>% mutate(token_5 = recode(token_5, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "cinco" = "5", "siete" = "7", "sieben" = "7", "seven" = "7", "six" = "6", "六" = "6"))

concreteness_replication <- concreteness_replication %>% mutate(
    token_4 = na_if(token_4, "0"))
concreteness_replication <- concreteness_replication %>% mutate(
    token_5 = na_if(token_5, "0"))

## This code checks which values are found in a given column (best would be only 1-7):
unique(concreteness_replication$token_1)
unique(concreteness_replication$token_2)
unique(concreteness_replication$token_3)
unique(concreteness_replication$token_4)
unique(concreteness_replication$token_5)

### This code makes all columns numeric:
concreteness_replication$token_1 <- as.numeric(concreteness_replication$token_1) #=>Token-Columns
concreteness_replication$token_2 <- as.numeric(concreteness_replication$token_2)
concreteness_replication$token_3 <- as.numeric(concreteness_replication$token_3)
concreteness_replication$token_4 <- as.numeric(concreteness_replication$token_4)
concreteness_replication$token_5 <- as.numeric(concreteness_replication$token_5)
concreteness_replication$prob_1 <- as.numeric(concreteness_replication$prob_1) #=>Probability-columns
concreteness_replication$prob_2 <- as.numeric(concreteness_replication$prob_2)
concreteness_replication$prob_3 <- as.numeric(concreteness_replication$prob_3)
concreteness_replication$prob_4 <- as.numeric(concreteness_replication$prob_4)
concreteness_replication$prob_5 <- as.numeric(concreteness_replication$prob_5)

### this calculates how many tokens ended up being used for the weighted sum
concreteness_replication$n_tokens_used <- rowSums(!is.na(cbind(
  concreteness_replication$token_1,
  concreteness_replication$token_2,
  concreteness_replication$token_3,
  concreteness_replication$token_4,
  concreteness_replication$token_5)))

mean(concreteness_replication$n_tokens_used) ## 4.9993 tokens were used on average.
min(concreteness_replication$n_tokens_used) # 4 tokens was the minimum
max(concreteness_replication$n_tokens_used) # 5 tokens was the maximum (more is not possible)

### Now we will generate the weighted_sum based on the tokens and their probabilities:

concreteness <- function(concreteness_replication) {
  rowSums(cbind(
    concreteness_replication$token_1 * concreteness_replication$prob_1,
    concreteness_replication$token_2 * concreteness_replication$prob_2,
    concreteness_replication$token_3 * concreteness_replication$prob_3,
    concreteness_replication$token_4 * concreteness_replication$prob_4,
    concreteness_replication$token_5 * concreteness_replication$prob_5
  ), na.rm = TRUE)}

### This code will add the output as a column:
concreteness_replication$concreteness_replication <- concreteness(concreteness_replication)

concreteness_replication$concreteness_replication <- round(concreteness_replication$concreteness_replication, 2)

concreteness_replication <- concreteness_replication %>% select(concreteness_replication)
```


```{r}
### Sometimes the output file from OpenAI uses "/" insetad of "." seperators; using this line of code it defaults to the point seperator
names(valence_replication) <- gsub("/", ".", names(valence_replication))

### This reduces the dataframe to only the required columns: ##select for columns, distinct for rows
valence_replication <- valence_replication %>% distinct(custom_id, response.body.choices.0.logprobs.content.0.top_logprobs.0.token, response.body.choices.0.logprobs.content.0.top_logprobs.0.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.1.token, response.body.choices.0.logprobs.content.0.top_logprobs.1.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.2.token, response.body.choices.0.logprobs.content.0.top_logprobs.2.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.3.token, response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.4.token, response.body.choices.0.logprobs.content.0.top_logprobs.4.logprob)


### This renames the columns of the dataframe:
valence_replication <- valence_replication %>% rename(word_nr = custom_id, token_1 = response.body.choices.0.logprobs.content.0.top_logprobs.0.token, logprob_1 = response.body.choices.0.logprobs.content.0.top_logprobs.0.logprob, token_2 = response.body.choices.0.logprobs.content.0.top_logprobs.1.token, logprob_2 = response.body.choices.0.logprobs.content.0.top_logprobs.1.logprob, token_3 = response.body.choices.0.logprobs.content.0.top_logprobs.2.token, logprob_3 = response.body.choices.0.logprobs.content.0.top_logprobs.2.logprob, token_4 = response.body.choices.0.logprobs.content.0.top_logprobs.3.token, logprob_4 = response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, token_5 = response.body.choices.0.logprobs.content.0.top_logprobs.4.token, logprob_5 = response.body.choices.0.logprobs.content.0.top_logprobs.4.logprob)


### This generates the probabilities for a token based of the logprobability:
valence_replication$prob_1 <- exp(valence_replication$logprob_1)
valence_replication$prob_2 <- exp(valence_replication$logprob_2)
valence_replication$prob_3 <- exp(valence_replication$logprob_3)
valence_replication$prob_4 <- exp(valence_replication$logprob_4)
valence_replication$prob_5 <- exp(valence_replication$logprob_5)


### This code makes all token-columns to be characters. This is necessary for the next step.
valence_replication$token_1 <- as.character(valence_replication$token_1)
valence_replication$token_2 <- as.character(valence_replication$token_2)
valence_replication$token_3 <- as.character(valence_replication$token_3)
valence_replication$token_4 <- as.character(valence_replication$token_4)
valence_replication$token_5 <- as.character(valence_replication$token_5)


### This will clean the token_columns, since often they do not contain strictly numbers from 1-7 but also written numbers, or number from different languages. Sometimes even numbers outside of the range of 1-7, or words like "Neutral".
valence_replication <- valence_replication %>% mutate(token_2 = recode(token_2, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "four" = "4", "Neutral" = "0", "seventh" = "7", "02" = "2", "siete" = "7", "cinco" = "5", "vier" = "4", "Five" = "5", "sieben" = "7", "sixth" = "6", "One" = "1", "six" = "6", "seven" = "7", "₂" = "2", "I" = "1", "۳" = "3", "۲" = "2"))
valence_replication <- valence_replication %>% mutate(token_3 = recode(token_3, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "four" = "4", "Neutral" = "0", "seventh" = "7", "02" = "2", "siete" = "7", "cinco" = "5", "vier" = "4", "Five" = "5", "sieben" = "7", "sixth" = "6", "One" = "1", "six" = "6", "seven" = "7", "₂" = "2", "I" = "1", "۳" = "3", "۲" = "2"))
valence_replication <- valence_replication %>% mutate(token_4 = recode(token_4, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "four" = "4", "Neutral" = "0", "seventh" = "7", "02" = "2", "siete" = "7", "cinco" = "5", "vier" = "4", "Five" = "5", "sieben" = "7", "sixth" = "6", "One" = "1", "six" = "6", "seven" = "7", "₂" = "2", "I" = "1", "۳" = "3", "۲" = "2"))
valence_replication <- valence_replication %>% mutate(token_5 = recode(token_5, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "four" = "4", "Neutral" = "0", "seventh" = "7", "02" = "2", "siete" = "7", "cinco" = "5", "vier" = "4", "Five" = "5", "sieben" = "7", "sixth" = "6", "One" = "1", "six" = "6", "seven" = "7", "₂" = "2", "I" = "1", "۳" = "3", "۲" = "2"))

valence_replication <- valence_replication %>% mutate(
    token_3 = na_if(token_3, "0"))
valence_replication <- valence_replication %>% mutate(
    token_4 = na_if(token_4, "0"))
valence_replication <- valence_replication %>% mutate(
    token_5 = na_if(token_5, "0"))

## This code checks which values are found in a given column (best would be only 1-7):
unique(valence_replication$token_1)
unique(valence_replication$token_2)
unique(valence_replication$token_3)
unique(valence_replication$token_4)
unique(valence_replication$token_5)

### This code makes all columns numeric:
valence_replication$token_1 <- as.numeric(valence_replication$token_1) #=>Token-Columns
valence_replication$token_2 <- as.numeric(valence_replication$token_2)
valence_replication$token_3 <- as.numeric(valence_replication$token_3)
valence_replication$token_4 <- as.numeric(valence_replication$token_4)
valence_replication$token_5 <- as.numeric(valence_replication$token_5)
valence_replication$prob_1 <- as.numeric(valence_replication$prob_1) #=>Probability-columns
valence_replication$prob_2 <- as.numeric(valence_replication$prob_2)
valence_replication$prob_3 <- as.numeric(valence_replication$prob_3)
valence_replication$prob_4 <- as.numeric(valence_replication$prob_4)
valence_replication$prob_5 <- as.numeric(valence_replication$prob_5)

### this calculates how many tokens ended up being used for the weighted sum
valence_replication$n_tokens_used <- rowSums(!is.na(cbind(
  valence_replication$token_1,
  valence_replication$token_2,
  valence_replication$token_3,
  valence_replication$token_4,
  valence_replication$token_5)))

mean(valence_replication$n_tokens_used) ## 4.9749 tokens were used on average.
min(valence_replication$n_tokens_used) # 3 tokens was the minimum
max(valence_replication$n_tokens_used) # 5 tokens was the maximum (more is not possible)

### Now we will generate the weighted_sum based on the tokens and their probabilities:

concreteness <- function(valence_replication) {
  rowSums(cbind(
    valence_replication$token_1 * valence_replication$prob_1,
    valence_replication$token_2 * valence_replication$prob_2,
    valence_replication$token_3 * valence_replication$prob_3,
    valence_replication$token_4 * valence_replication$prob_4,
    valence_replication$token_5 * valence_replication$prob_5
  ), na.rm = TRUE)}

### This code will add the output as a column:
valence_replication$valence_replication <- concreteness(valence_replication)

valence_replication$valence_replication <- round(valence_replication$valence_replication, 2)


valence_replication <- valence_replication %>% select(valence_replication)
```


```{r}
names(arousal_replication) <- gsub("/", ".", names(arousal_replication))

### This reduces the dataframe to only the required columns: ##select for columns, distinct for rows
arousal_replication <- arousal_replication %>% distinct(custom_id, response.body.choices.0.logprobs.content.0.top_logprobs.0.token, response.body.choices.0.logprobs.content.0.top_logprobs.0.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.1.token, response.body.choices.0.logprobs.content.0.top_logprobs.1.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.2.token, response.body.choices.0.logprobs.content.0.top_logprobs.2.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.3.token, response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, response.body.choices.0.logprobs.content.0.top_logprobs.4.token, response.body.choices.0.logprobs.content.0.top_logprobs.4.logprob)


### This renames the columns of the dataframe:
arousal_replication <- arousal_replication %>% rename(word_nr = custom_id, token_1 = response.body.choices.0.logprobs.content.0.top_logprobs.0.token, logprob_1 = response.body.choices.0.logprobs.content.0.top_logprobs.0.logprob, token_2 = response.body.choices.0.logprobs.content.0.top_logprobs.1.token, logprob_2 = response.body.choices.0.logprobs.content.0.top_logprobs.1.logprob, token_3 = response.body.choices.0.logprobs.content.0.top_logprobs.2.token, logprob_3 = response.body.choices.0.logprobs.content.0.top_logprobs.2.logprob, token_4 = response.body.choices.0.logprobs.content.0.top_logprobs.3.token, logprob_4 = response.body.choices.0.logprobs.content.0.top_logprobs.3.logprob, token_5 = response.body.choices.0.logprobs.content.0.top_logprobs.4.token, logprob_5 = response.body.choices.0.logprobs.content.0.top_logprobs.4.logprob)


### This generates the probabilities for a token based of the logprobability:
arousal_replication$prob_1 <- exp(arousal_replication$logprob_1)
arousal_replication$prob_2 <- exp(arousal_replication$logprob_2)
arousal_replication$prob_3 <- exp(arousal_replication$logprob_3)
arousal_replication$prob_4 <- exp(arousal_replication$logprob_4)
arousal_replication$prob_5 <- exp(arousal_replication$logprob_5)


### This code makes all token-columns to be characters. This is necessary for the next step.
arousal_replication$token_1 <- as.character(arousal_replication$token_1)
arousal_replication$token_2 <- as.character(arousal_replication$token_2)
arousal_replication$token_3 <- as.character(arousal_replication$token_3)
arousal_replication$token_4 <- as.character(arousal_replication$token_4)
arousal_replication$token_5 <- as.character(arousal_replication$token_5)


### This will clean the token_columns, since often they do not contain strictly numbers from 1-7 but also written numbers, or number from different languages. Sometimes even numbers outside of the range of 1-7, or words like "Neutral".



arousal_replication <- arousal_replication %>% mutate(token_2 = recode(token_2, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "<|end|>" = "0", "Seven" = "7", "sieben" = "7", "seven" = "7", "Neutral" = "0", "seventh" = "7", "four" = "4", "six" = "6", "cinco" = "5", "siete" = "7", "02" = "2", "۲" = "2", "۳" = "3", "四" = "4"))
arousal_replication <- arousal_replication %>% mutate(token_3 = recode(token_3, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "<|end|>" = "0", "Seven" = "7", "sieben" = "7", "seven" = "7", "Neutral" = "0", "seventh" = "7", "four" = "4", "six" = "6", "cinco" = "5", "siete" = "7", "02" = "2", "۲" = "2", "۳" = "3", "四" = "4"))
arousal_replication <- arousal_replication %>% mutate(token_4 = recode(token_4, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "<|end|>" = "0", "Seven" = "7", "sieben" = "7", "seven" = "7", "Neutral" = "0", "seventh" = "7", "four" = "4", "six" = "6", "cinco" = "5", "siete" = "7", "02" = "2", "۲" = "2", "۳" = "3", "四" = "4"))
arousal_replication <- arousal_replication %>% mutate(token_5 = recode(token_5, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "７" = "7", "<|end|>" = "0", "Seven" = "7", "sieben" = "7", "seven" = "7", "Neutral" = "0", "seventh" = "7", "four" = "4", "six" = "6", "cinco" = "5", "siete" = "7", "02" = "2", "۲" = "2", "۳" = "3", "四" = "4"))

arousal_replication <- arousal_replication %>% mutate(
    token_4 = na_if(token_4, "0"))
arousal_replication <- arousal_replication %>% mutate(
    token_5 = na_if(token_5, "0"))

## This code checks which values are found in a given column (best would be only 1-7):
unique(arousal_replication$token_1)
unique(arousal_replication$token_2)
unique(arousal_replication$token_3)
unique(arousal_replication$token_4)
unique(arousal_replication$token_5)

### This code makes all columns numeric:
arousal_replication$token_1 <- as.numeric(arousal_replication$token_1) #=>Token-Columns
arousal_replication$token_2 <- as.numeric(arousal_replication$token_2)
arousal_replication$token_3 <- as.numeric(arousal_replication$token_3)
arousal_replication$token_4 <- as.numeric(arousal_replication$token_4)
arousal_replication$token_5 <- as.numeric(arousal_replication$token_5)
arousal_replication$prob_1 <- as.numeric(arousal_replication$prob_1) #=>Probability-columns
arousal_replication$prob_2 <- as.numeric(arousal_replication$prob_2)
arousal_replication$prob_3 <- as.numeric(arousal_replication$prob_3)
arousal_replication$prob_4 <- as.numeric(arousal_replication$prob_4)
arousal_replication$prob_5 <- as.numeric(arousal_replication$prob_5)

### this calculates how many tokens ended up being used for the weighted sum
arousal_replication$n_tokens_used <- rowSums(!is.na(cbind(
  arousal_replication$token_1,
  arousal_replication$token_2,
  arousal_replication$token_3,
  arousal_replication$token_4,
  arousal_replication$token_5)))

mean(arousal_replication$n_tokens_used) ## 4.9788 tokens were used on average.
min(arousal_replication$n_tokens_used) # 4 tokens was the minimum
max(arousal_replication$n_tokens_used) # 5 tokens was the maximum (more is not possible)

### Now we will generate the weighted_sum based on the tokens and their probabilities:

arousal <- function(arousal_replication) {
  rowSums(cbind(
    arousal_replication$token_1 * arousal_replication$prob_1,
    arousal_replication$token_2 * arousal_replication$prob_2,
    arousal_replication$token_3 * arousal_replication$prob_3,
    arousal_replication$token_4 * arousal_replication$prob_4,
    arousal_replication$token_5 * arousal_replication$prob_5
  ), na.rm = TRUE)}

### This code will add the output as a column:
arousal_replication$arousal_replication <- arousal(arousal_replication)

arousal_replication$arousal_replication <- round(arousal_replication$arousal_replication, 2)


arousal_replication <- arousal_replication %>% select(arousal_replication)
```

## age of acquisition


```{r}
aoa_replication <- aoa_replication %>% select(aoa)
aoa_replication <- aoa_replication %>% rename("aoa_replication" = "aoa")

```

## correlation to check for replicability of GPT estimates

```{r}
corr <- rep_data %>% select(GPT_FAM, GPT_concr, GPT_val, GPT_arou, GPT_AoA_ft)
corr <- cbind(corr, arousal_replication, concreteness_replication, familiarity_replication, valence_replication, aoa_replication)

## pearson
round(cor(corr$familiarity_replication, corr$GPT_FAM, method = "pearson"), 2) #0.99
round(cor(corr$concreteness_replication, corr$GPT_concr, method = "pearson"), 2) #0.99
round(cor(corr$valence_replication, corr$GPT_val, method = "pearson"), 2) # 0.99
round(cor(corr$arousal_replication, corr$arousal_replication, method = "pearson"), 2) #1.00
round(cor(corr$aoa_replication, corr$GPT_AoA_ft, method = "pearson"), 2) #0.98

## spearman:
round(cor(corr$familiarity_replication, corr$GPT_FAM, method = "spearman"), 2) #0.98
round(cor(corr$concreteness_replication, corr$GPT_concr, method = "spearman"), 2) #0.99
round(cor(corr$valence_replication, corr$GPT_val, method = "spearman"), 2) #0.99
round(cor(corr$arousal_replication, corr$arousal_replication, method = "spearman"), 2) #1.00
round(cor(corr$aoa_replication, corr$GPT_AoA_ft, method = "spearman"), 2) #0.98
```
